controller_list:
  - name: fake_scorbot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - pitch_joint
      - roll_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - roll_joint
      - pad1_joint
      - pad2_joint
initial:  # Define initial robot poses.
  - group: scorbot_arm
    pose: home
  - group: gripper
    pose: gripper_open