# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: scorbot_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - pitch_joint
    - roll_joint
    - pad1_joint
    - pad2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
scorbot_control:
  type: position_controllers/JointPositionController
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - pitch_joint
    - roll_joint
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1