TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.1
  escape_vel: -0.2

  acc_lim_theta: 0.25
  acc_lim_x: 0.25
  acc_lim_Y: 0.25

  holonomic_robot: false

  meter_scoring: true
