map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.32, -0.36], [-0.32, 0.36], [0.32, 0.36], [0.32, -0.36]]

transform_tolerance: 1.0

inflation_radius: 0.35

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

