scaled_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scorbot_base_joint
    - scorbot_shoulder_joint
    - scorbot_elbow_joint
    - scorbot_pitch_joint
    - scorbot_roll_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    scorbot_joint_1: {trajectory: 0.1, goal: 0.1}
    scorbot_joint_2: {trajectory: 0.1, goal: 0.1}
    scorbot_joint_3: {trajectory: 0.1, goal: 0.1}
    scorbot_joint_4: {trajectory: 0.1, goal: 0.1}
    scorbot_joint_5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
